= Annotation 
劉育辰 <torr@tist.com.tw>
v1.0, 2020-05-31
:experimental:
:icons: font
:sectnums:
:toc: left
:toc-title: 大綱
:sectanchors:

== Concept

. Annotation (註解) 如同一張標籤，如同課本上用螢光筆標記起來的部分。 +
主要是提醒或幫助你快速地理解被標註的物件的大致作用。

. 註解不是程式碼的一部分，註解對於程式碼運行的效果沒有直接影響。

== Create an Annotation

=== syntax

* 跟介面的形式很像，只是前面多個@符號。
+
[source,java]
--
public @interface MyAnnotation {

}
--

=== meta-annotation

* 用來標註 @interface 的Annotation，主要是用來指定範圍及作用目標。
* meta-annotation
+
[cols="2,5,5"]
|===
^.^|meta-annotation ^.^|describe ^.^|values

|★@Retention
| how the marked annotation is stored +
說明了這個註解的的存活時間
a|* RetentionPolicy.SOURCE +
只在source code階段保留，編譯時將被忽略
* RetentionPolicy.CLASS +
只被保留到編譯階段，後續運行無法取得
* RetentionPolicy.RUNTIME +
會被加載進JVM，程式運行時能夠獲取


|@Documented
| indicates that whenever the specified annotation is used those elements should be documented using the Javadoc tool. +
無論這個註解有沒有被使用，他都會被Java doc 產生工具gen出來
^.^| --

|★@Target
| restrict what kind of Java elements the annotation can be applied to. +
決定Annotation 可以使用的目標

a|* ElementType.ANNOTATION_TYPE 註解
* ElementType.CONSTRUCTOR 建構子
* ElementType.FIELD 屬性
* ElementType.LOCAL_VARIABLE 區域變數
* ElementType.METHOD 方法
* ElementType.PARAMETER 方法參數
* ElementType.PACKAGE can be applied to a package declaration.
* ElementType.TYPE 類別

|@Inherited
|the annotation type can be inherited from the super class. +
A類別使用了被@Inherited標記的註解(@XXX)，當B類別繼承A時，B也會有這個註解(@XXX)的效果。
^.^| --

|@Repeatable
|introduced in Java SE 8, indicates that the marked annotation can be applied more than once to the same declaration or type use. +
在同一個目標上，多次標記同一個註解。(ex.角色)
^.^| --

|===

★ -> 通常這兩個一定會寫

=== field

* Annotation 只有屬性沒有方法，但宣告時候需要以無參數方法形式宣告，同時可以賦予預設值，例如：
+
[source,java]
--
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.FIELD)
public @interface MyAnnotation {

    String name() default "torr";

}
--

* 若Annotation 只有一個名為 String value() 的屬性時，使用時可以直接填寫屬性值，不用寫屬性名稱。
+
[source,java]
--
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.TYPE)
public @interface MyClassType {

    String value();

}
--
+
[source,java]
--
@MyClassType("TestClass")
public class Test {

}
--

* 一個註解沒有任何屬性，使用時可省略小括號
+
[source,java]
--
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.TYPE)
public @interface Perform {
}
--
+
[source,java]
--
@Perform
public class PerformSomething {
    // 略...
}
--

== How to use Annotation

IMPORTANT: 注意這裡才是Annotation 的重頭戲。

=== Reflection

* 前言 +
前面提到：註解不是程式碼的一部分，對於程式碼運行的效果沒有直接影響。 +
建立了註解之後，開發者必須撰寫相應的程式區塊進而提取並處理 Annotation 信息，該註解才有了真正意義上的用途。

* 在程式碼中，想要取得Annotation 訊息，咱們就得透過Java's Reflection API.
** 透過 變數.getClass() 取得自己的Class 物件，其中就有
``getAnnotation(Class<A> annotationClass)、getAnnotations()`` 等方法以取得Annotation/ Annotation[]

** Class 物件，可以再進一步getDeclaredFields() 取得已宣告屬性 Field[]。 +
或是getDeclaredMethods()取得已宣告方法 Method[]。 +
兩者皆有``getAnnotation(Class<T> annotationClass)``方法可以取被標記的Annotation

** Class、Field、Method 皆可以使用 ``isAnnotationPresent(Class<? extends Annotation> annotationClass)``
來判斷是否有被某Annotation標記

* 簡單範例
+
[source,java]
--
public class MyAnnotationValidator {

    private void checkIfMyAnnotation(Object object) {
        if (Objects.isNull(object)) {
            throw new MyException("The object to serialize is null");
        }

        Class<?> clazz = object.getClass();
        if (!clazz.isAnnotationPresent(MyAnnotation.class)) { //<1>
            // 你的處理...
        }

        for (Field field : clazz.getDeclaredFields()) {
            if (field.isAnnotationPresent(JsonElement.class)) {  //<1>
                field.setAccessible(true); // <2>
                // do something...
            }
        }

        for (Method method : clazz.getDeclaredMethods()) {
            if (method.isAnnotationPresent(Init.class)) { //<1>
                method.setAccessible(true); // <2>
                // do something...
            }
        }
    }
}
--
<1> 以isAnnotationPresent 判斷是否有某一註解
<2> 需要將field/ method setAccessible(true) 後才能操作

== Conclusion

* 官方文件
+
[quote,'https://docs.oracle.com/javase/tutorial/java/annotations/[Java 官方文件]
']

____
Annotations, a form of metadata, provide data about a program that is not part of the program itself.
Annotations have no direct effect on the operation of the code they annotate.
____
+
註解是一種形式的metadata，用來解釋某段程式，因此註解並非程式本身的一部分，所以才對於程式運行的效果沒有直接影響。

* 註解用處
** 提供信息給編譯器，編譯器可以利用註解來探測錯誤和警告訊息
** 編譯階段時的處理，軟體工具可以用來利用註解信息來生成代碼、Html文檔或者做其它相應處理。
** 運行時的處理，某些註解可以在程序運行的時候接受代碼的提取
** 當開發者使用Annotation 修飾了類別、方法、Field 等成員之後，這些 Annotation 不會自己生效，必須由開發者提供相應的代碼來提取並處理 Annotation 信息。這些處理提取和處理 Annotation 的代碼統稱為 APT（Annotation Processing Tool)。

IMPORTANT: 現在，我們可以給自己答案了，註解有什麼用？ +
給 編譯器 或者 APT 用的。

== Reference

. link:https://kknews.cc/code/agono4n.html[Java 註解（Annotation）你可以這樣學]
. link:https://www.baeldung.com/java-custom-annotation[Creating a Custom Annotation in Java | Baeldung]
. link:https://docs.oracle.com/javase/tutorial/java/annotations/[Java 官方文件]
