spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1 #內存
    username: sa
    password:
    driver-class-name: org.h2.Driver
    hikari:
      maximum-pool-size: 10
  h2:
    console:
      enabled: true
      path: /h2

  jpa:
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  freemarker:
    enabled: true
    cache: true
    suffix: .ftl
    settings:
      template_exception_handler: ignore
    template-loader-path: classpath:/templates

server:
  port: 8081
  servlet:
    session:
      timeout: 6000